version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: npm install
      - run: npm run prepublish
      - run:
          name: Tar Deploy
          command: |
            sudo tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./package.json ./dist/*
      - run: sudo npm install -g caprover
      - run: echo $CAPROVER_PASSWORD
      - run:
          name: Caprover Deploy
          command: |
            sudo caprover deploy -h $CAPROVER_SERVER -t ./deploy.tar -p $CAPROVER_PASSWORD -a toc
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
